name: Python CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: check out code
              uses: actions/checkout@v4

            - name: Set up Python 3.11
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install ruff # Install Ruff (a fast linter)
                # Adjust the path to your requirements.txt if needed
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Lint with ruff
              run: |
                ruff check server/
        